# ------------------------------------------------------------------------------
# Prisma:
# ------------------------------------------------------------------------------

serviceAccount:
  name: 'prisma-orm'

database:
  user: prisma
  password: 'prisma'

auth:
  enabled: true
  secret: 'some-secret'

# ------------------------------------------------------------------------------
# PostgreSQL:
# ------------------------------------------------------------------------------

postgresql:
  enabled: true
  imageTag: '10'

  persistence:
    enabled: true

  postgresUser: prisma
  postgresPassword: 'prisma'
